package hocvan.entity;
// Generated Oct 19, 2020 2:39:47 PM by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Slide generated by hbm2java
 */
@Entity
@Table(name = "slide", catalog = "hocvan", uniqueConstraints = @UniqueConstraint(columnNames = "position"))
public class Slide implements java.io.Serializable {

	private int id;
	private String imageName;
	private String imagePath;
	private Integer position;

	public Slide() {
	}

	public Slide(int id) {
		this.id = id;
	}

	public Slide(int id, String imageName, String imagePath, Integer position) {
		this.id = id;
		this.imageName = imageName;
		this.imagePath = imagePath;
		this.position = position;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "image_name")
	public String getImageName() {
		return this.imageName;
	}

	public void setImageName(String imageName) {
		this.imageName = imageName;
	}

	@Column(name = "image_path", length = 2000)
	public String getImagePath() {
		return this.imagePath;
	}

	public void setImagePath(String imagePath) {
		this.imagePath = imagePath;
	}

	@Column(name = "position", unique = true)
	public Integer getPosition() {
		return this.position;
	}

	public void setPosition(Integer position) {
		this.position = position;
	}

}
